"""Generate the 15-platform × workflows mapping table for /impetus/autonomy/.

Per docs/impetus-restructure-spec.md §8.1 §06:
  "Table · 15 platforms × workflow rows they enable.
   Each row: platform name · workflows it powers · today's level
   · target in 90 days · DRI for the move."

Reads data/impetus/*.yaml progress blocks and writes the table fragment
into impetus/autonomy/index.html between BEGIN/END markers.

Run:  .venv/bin/python tools/build_autonomy_table.py
"""

from __future__ import annotations

import html
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "impetus"
PAGE = ROOT / "impetus" / "autonomy" / "index.html"

H = html.escape
LEVEL_NAMES = ["Manual", "Assisted", "Augmented", "Intelligent", "Agentic", "Autonomous"]

# Order must match the platform card grid in /impetus/index.html (the canonical 15)
PLATFORM_ORDER = [
    "cortex", "intelliloom", "plm", "nextwave", "costing-engine", "master-hub",
    "intelliverse", "uvp", "recollect", "gmetri", "pulsepoint",
    "companion-app", "ai-photoshoot", "analytics", "instadesk",
]


def md_inline(text: str) -> str:
    return re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", H(text or ""))


def lvl_pill(lvl: int | None) -> str:
    if lvl is None:
        return '<span class="lvl-pill" style="background:#E5E5E5;color:#9CA3AF;">—</span>'
    return f'<span class="lvl-pill alvl-{lvl}">L{lvl} · {LEVEL_NAMES[lvl]}</span>'


def render_workflow_chips(workflows: list[dict]) -> str:
    if not workflows:
        return '<span style="color:var(--ink-soft);font-style:italic;">cross-cutting infrastructure · no single workflow</span>'
    chips = []
    for w in workflows:
        number = w.get("number", "")
        name = w.get("name", "")
        anchor = number.replace(".", "-") if number else name.lower().replace(" ", "-")
        n = f'<span class="wf-num">§{H(number)}</span> ' if number else ""
        chips.append(f'<a href="#matrix-{H(anchor)}" class="wf-chip">{n}{H(name)}</a>')
    return "".join(chips)


def render_workflow_targets(workflows: list[dict]) -> tuple[str, str]:
    """Return (current_summary, target_summary) — pills per workflow row."""
    if not workflows:
        return ("—", "—")
    cur_pills = "".join(f'<div class="cell-row">{lvl_pill(w.get("current"))}</div>' for w in workflows)
    tgt_pills = "".join(f'<div class="cell-row">{lvl_pill(w.get("target"))}</div>' for w in workflows)
    return (cur_pills, tgt_pills)


def build_table() -> str:
    rows = []
    for i, slug in enumerate(PLATFORM_ORDER, start=1):
        yp = DATA_DIR / f"{slug}.yaml"
        if not yp.exists():
            print(f"  ! missing data/impetus/{slug}.yaml — skipping")
            continue
        data = yaml.safe_load(yp.read_text())
        title = data.get("title", slug)
        sub = data.get("sub_title", "")
        prog = data.get("progress", {}) or {}
        cur_level = prog.get("current_level")
        workflows = prog.get("workflows", []) or []

        platform_cell = f"""
<div class="pf-name"><a href="/impetus/{H(slug)}">{H(title)}</a></div>
{f'<div class="pf-sub">{H(sub)}</div>' if sub else ''}
<div class="pf-today">Today · {lvl_pill(cur_level)}</div>
"""
        wf_cell = render_workflow_chips(workflows)
        cur_cell, tgt_cell = render_workflow_targets(workflows)

        rows.append(f"""
<tr>
  <td class="num">{i:02d}</td>
  <td class="platform">{platform_cell}</td>
  <td class="workflows">{wf_cell}</td>
  <td class="levels">{cur_cell}</td>
  <td class="levels">{tgt_cell}</td>
  <td class="dri">TBD</td>
</tr>
""")

    return f"""
<table class="platform-matrix">
  <thead>
    <tr>
      <th style="width:36px;">#</th>
      <th>Platform</th>
      <th>Workflows it powers</th>
      <th style="width:170px;">Today</th>
      <th style="width:170px;">90-day target</th>
      <th style="width:110px;">DRI for the move</th>
    </tr>
  </thead>
  <tbody>{''.join(rows)}</tbody>
</table>
"""


def update_page() -> None:
    if not PAGE.exists():
        print(f"  ! {PAGE} not found")
        return
    content = PAGE.read_text()
    table = build_table()

    BEGIN = "<!-- BEGIN platform-matrix · auto-generated by tools/build_autonomy_table.py -->"
    END = "<!-- END platform-matrix -->"
    block = f"{BEGIN}\n{table}\n{END}"

    if BEGIN in content and END in content:
        new = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END),
            block,
            content,
            flags=re.DOTALL,
        )
        PAGE.write_text(new)
        print(f"  updated {PAGE.relative_to(ROOT)}  ({len(table):,} bytes of table)")
    else:
        print(f"  ! markers not found in {PAGE} — add the BEGIN/END comments first")


if __name__ == "__main__":
    update_page()
